### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tehTK** [codefori/vscode-rpgle#336]
Hello, 
while working with a extremely large Repository The RPGLE extension crashes at the startup of VSCode. 
With all the generated content and code there are 136902 RPGLE files in this repository. 

```
RangeError: Maximum call stack size exceeded
    at c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\server.js:1:292658
    at Array.forEach (<anonymous>)
    at c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\server.js:1:292442
    at Generator.next (<anonymous>)
    at i (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\server.js:1:278751)
```
```
Node.js v20.16.0
[Info  - 8:00:37 AM] Connection to server got closed. Server will restart.
[Error - 8:00:37 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:57915)
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138009)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138222)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:198593)
	at t (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:136311)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at Y (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:47173)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at d.fireClose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:68172)
	at ChildProcess.<anonymous> (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:79138)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
[Error - 8:00:37 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:57915)
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138009)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138222)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:198593)
	at t (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:136311)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at Y (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:47173)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at d.fireClose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:68172)
	at ChildProcess.<anonymous> (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:79138)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
[Error - 8:00:37 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:57915)
	at Object.dispose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138009)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:138222)
	at T.handleConnectionClosed (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:198593)
	at t (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:136311)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at Y (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:47173)
	at r.invoke (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:59529)
	at o.fire (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:60290)
	at d.fireClose (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:68172)
	at ChildProcess.<anonymous> (c:\Users\myUser\.vscode\extensions\halcyontechltd.vscode-rpgle-0.26.12\out\extension.js:1:79138)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Project Mode enabled: true
Starting search of: c:\Users\myUser\repository\myRepo
Found RPGLE files: 136902
```

**Comment by worksofliam** [comment]
We have made some major improvements to sizing issues in 0.28.0, which will be out next week. I think that might solve this issue.

**Comment by tehTK** [comment]
We also worked on our repo to make it smaller and since December, I have not seen any crash with this error message.
